/**
 * Director utilities — re-exports core edit-map logic + export/copy helpers.
 */

export { parseToSegments, generateEditMap, fmtTime } from "./edit-map";

/**
 * Export director segments as JSON download.
 */
export function exportDirectorJSON(segments, format, duration) {
  const data = {
    version: "2.0",
    app: "Celeste Director",
    exportedAt: new Date().toISOString(),
    format,
    duration,
    segmentCount: segments.length,
    segments,
  };
  downloadBlob(
    new Blob([JSON.stringify(data, null, 2)], { type: "application/json" }),
    `celeste-director_${Date.now()}.json`
  );
}

/**
 * Export director segments as TXT download.
 */
export function exportDirectorTXT(segments, format) {
  const lines = [];
  const hr = "=".repeat(55);
  const hr2 = "-".repeat(40);

  lines.push(hr);
  lines.push("CELESTE — DIRECTOR EDIT MAP");
  lines.push(hr);
  lines.push(`Format: ${format}`);
  lines.push(`Segments: ${segments.length}`);
  lines.push(
    `Duration: ${segments.length > 0 ? segments[segments.length - 1].end : 0}s`
  );
  lines.push(`Exported: ${new Date().toLocaleString("es-AR")}`);
  lines.push("");

  for (const seg of segments) {
    lines.push(hr2);
    lines.push(`SEGMENT ${seg.id} [${fmtSec(seg.start)}\u2013${fmtSec(seg.end)}]`);
    lines.push(`  Text: ${seg.text.slice(0, 120)}`);
    if (seg.motion) lines.push(`  Motion: ${seg.motion.label} \u2014 ${seg.motion.reason}`);
    if (seg.broll) lines.push(`  B-Roll: "${seg.broll.query}"`);
    if (seg.sfx) lines.push(`  SFX: ${seg.sfx.effect} (${seg.sfx.intensity})`);
    if (seg.onScreenText) lines.push(`  On-Screen: ${seg.onScreenText}`);
    if (seg.notes) lines.push(`  Notes: ${seg.notes}`);
  }

  lines.push("");
  lines.push(hr2);
  lines.push("B-ROLL SHOPPING LIST:");
  segments
    .filter((s) => s.broll)
    .forEach((s, i) => {
      lines.push(`  ${i + 1}. [${fmtSec(s.start)}\u2013${fmtSec(s.end)}] ${s.broll.query}`);
    });

  lines.push("");
  lines.push("SFX:");
  const uniqueSfx = [
    ...new Set(
      segments.filter((s) => s.sfx).map((s) => `${s.sfx.effect} (${s.sfx.intensity})`)
    ),
  ];
  uniqueSfx.forEach((s, i) => {
    lines.push(`  ${i + 1}. ${s}`);
  });

  lines.push("");
  lines.push(hr);
  lines.push("Generated by Celeste Director");
  lines.push(hr);

  downloadBlob(
    new Blob([lines.join("\n")], { type: "text/plain;charset=utf-8" }),
    `celeste-director_${Date.now()}.txt`
  );
}

/**
 * Copy director segments summary to clipboard.
 */
export async function copyDirectorToClipboard(segments) {
  const text = segments
    .map((seg) => {
      const parts = [`[${fmtSec(seg.start)}\u2013${fmtSec(seg.end)}] ${seg.text.slice(0, 80)}`];
      if (seg.motion) parts.push(`  Motion: ${seg.motion.label}`);
      if (seg.broll) parts.push(`  B-Roll: ${seg.broll.query}`);
      if (seg.sfx) parts.push(`  SFX: ${seg.sfx.effect}`);
      return parts.join("\n");
    })
    .join("\n\n");

  await navigator.clipboard.writeText(text);
}

/* Internal helpers */

function fmtSec(sec) {
  const m = Math.floor(sec / 60);
  const s = Math.floor(sec % 60);
  return `${m}:${s.toString().padStart(2, "0")}`;
}

function downloadBlob(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
