/**
 * Subtitle / export format generators for EDL segments.
 */

/**
 * Format seconds to SRT timestamp (HH:MM:SS,mmm).
 */
function srtTime(sec) {
  const h = Math.floor(sec / 3600);
  const m = Math.floor((sec % 3600) / 60);
  const s = Math.floor(sec % 60);
  const ms = Math.round((sec % 1) * 1000);
  return (
    String(h).padStart(2, "0") + ":" +
    String(m).padStart(2, "0") + ":" +
    String(s).padStart(2, "0") + "," +
    String(ms).padStart(3, "0")
  );
}

/**
 * Generate SRT subtitle string from EDL segments.
 * @param {{ id: string, start: number, end: number, vo: string }[]} segments
 * @returns {string}
 */
export function generateSRT(segments) {
  return segments
    .map((seg, i) => [
      i + 1,
      `${srtTime(seg.start)} --> ${srtTime(seg.end)}`,
      seg.vo,
      "",
    ].join("\n"))
    .join("\n");
}

/**
 * Generate a shotlist TXT from EDL segments.
 * @param {{ id: string, start: number, end: number, vo: string, on_screen: string, broll_query: string, motion: object }[]} segments
 * @returns {string}
 */
export function generateShotlist(segments) {
  const lines = ["SHOTLIST", "=" .repeat(40), ""];
  segments.forEach((seg, i) => {
    const dur = seg.end - seg.start;
    lines.push(`SHOT ${i + 1}  [${fmtMM(seg.start)} - ${fmtMM(seg.end)}]  (${dur}s)`);
    lines.push(`  VO: ${seg.vo}`);
    if (seg.on_screen) lines.push(`  ON SCREEN: ${seg.on_screen}`);
    if (seg.broll_query) lines.push(`  B-ROLL: ${seg.broll_query}`);
    if (seg.motion?.type) lines.push(`  MOTION: ${seg.motion.type}`);
    if (seg.sfx?.length) lines.push(`  SFX: ${seg.sfx.join(", ")}`);
    if (seg.transition?.type) lines.push(`  TRANSITION: ${seg.transition.type}`);
    lines.push("");
  });
  lines.push(`TOTAL: ${segments.length} shots`);
  return lines.join("\n");
}

function fmtMM(sec) {
  const m = Math.floor(sec / 60);
  const s = Math.floor(sec % 60);
  return `${m}:${String(s).padStart(2, "0")}`;
}

/**
 * Generate a script markdown from title + text.
 * @param {string} title
 * @param {string} scriptText
 * @returns {string}
 */
export function generateScriptMD(title, scriptText) {
  return [
    `# ${title}`,
    "",
    `> Generated by Celeste — ${new Date().toLocaleDateString("es-AR")}`,
    "",
    "---",
    "",
    scriptText,
    "",
  ].join("\n");
}
